from base_types import Item

ITEMS = [
    Item(
        id=1,
        title="Chanel Classic Flap Bag",
        description="Iconic quilted lambskin bag with chain strap and CC turn-lock",
        price=8500.00,
        image_url="https://sothebys-com.brightspotcdn.com/b6/01/91febf0e42e381409de6b94f4259/copy-of-untitled-64.jpg",
    ),
    Item(
        id=2,
        title="Hermès Birkin Leather Handbag",
        description="Handcrafted luxury tote in premium calfskin leather",
        price=12500.00,
        image_url="https://theluxuryflavor.com/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-25-at-3.30.12-PM.jpeg",
    ),
    Item(
        id=3,
        title="Louis Vuitton Neverfull MM Tote",
        description="Spacious monogram canvas tote with leather trim and adjustable straps",
        price=1850.00,
        image_url="https://theluxuryflavor.com/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-25-at-3.30.12-PM.jpeg",
    ),
    Item(
        id=4,
        title="Gucci Dionysus Shoulder Bag",
        description="Embroidered leather shoulder bag with signature tiger head closure",
        price=3200.00,
        image_url="https://di2ponv0v5otw.cloudfront.net/posts/2025/06/25/685c70612326c83abec7497e/m_685c707cd8024c7e6a998fd2.jpg",
    ),
    Item(
        id=5,
        title="Dior Lady Dior Handbag",
        description="Quilted lambskin bag with iconic Dior charms and top handles",
        price=5500.00,
        image_url="https://medias.collectorsquare.com/images/products/412065/00pp-dior-lady-dior-small-model-handbag-in-green-leather-cannage.jpg",
    ),
    Item(
        id=6,
        title="Burberry Check Canvas Tote",
        description="Classic canvas tote with signature check pattern and leather trim",
        price=1490.00,
        image_url="https://theluxuryflavor.com/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-25-at-3.30.12-PM.jpeg",
    ),
    Item(
        id=7,
        title="Bottega Veneta Intrecciato Hobo",
        description="Woven leather hobo bag with signature intrecciato craftsmanship",
        price=3900.00,
        image_url="https://theluxuryflavor.com/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-25-at-3.30.12-PM.jpeg",
    ),
    Item(
        id=8,
        title="Louis Vuitton Speedy Bandoulière",
        description="Classic Boston bag in monogram canvas with detachable shoulder strap",
        price=1760.00,
        image_url="https://theluxuryflavor.com/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-25-at-3.30.12-PM.jpeg",
    ),
    Item(
        id=9,
        title="Fendi Baguette Shoulder Bag",
        description="Compact shoulder bag with FF logo clasp and embellished design",
        price=3650.00,
        image_url="https://theluxuryflavor.com/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-25-at-3.30.12-PM.jpeg",
    ),
    Item(
        id=10,
        title="Versace Medusa Clutch",
        description="Evening clutch with gold Medusa emblem and chain strap",
        price=1850.00,
        image_url="https://theluxuryflavor.com/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-25-at-3.30.12-PM.jpeg",
    ),
    Item(
        id=11,
        title="Yves Saint Laurent Kate Bag",
        description="Sleek leather shoulder bag with YSL logo and tassel detail",
        price=2450.00,
        image_url="https://theluxuryflavor.com/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-25-at-3.30.12-PM.jpeg",
    ),
    Item(
        id=12,
        title="Prada Galleria Saffiano Tote",
        description="Structured tote in signature Saffiano leather with metal hardware",
        price=3200.00,
        image_url="https://theluxuryflavor.com/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-25-at-3.30.12-PM.jpeg",
    ),
    Item(
        id=13,
        title="Givenchy Antigona Bag",
        description="Structured leather tote with geometric design and top handles",
        price=2590.00,
        image_url="https://theluxuryflavor.com/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-25-at-3.30.12-PM.jpeg",
    ),
    Item(
        id=14,
        title="Balenciaga City Bag",
        description="Soft leather bag with signature studded details and adjustable strap",
        price=2150.00,
        image_url="https://theluxuryflavor.com/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-25-at-3.30.12-PM.jpeg",
    ),
    Item(
        id=15,
        title="Hermès Kelly Bag",
        description="Elegant trapezoid handbag with turn-lock closure and top handle",
        price=10800.00,
        image_url="https://theluxuryflavor.com/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-25-at-3.30.12-PM.jpeg",
    ),
]
